# Travis CI Java documentation can be found in:
# https://docs.travis-ci.com/user/languages/java/

# https://docs.travis-ci.com/user/reference/overview/#linux
dist: xenial

# This enables the 'defaults' to test java applications:
language: java

# https://docs.travis-ci.com/user/reference/xenial/#jvm-clojure-groovy-java-scala-support
jdk:
 - openjdk8

cache:
  directories:
    - $HOME/.m2

# https://docs.travis-ci.com/user/job-lifecycle/
script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P '!oss-release,travis-ci'
  - mvn test -DskipTests=false -B -P '!oss-release,travis-ci'

# tip: export CODECOV_TOKEN="xxx"
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)

before_script:
  - git config --global core.autocrlf input

